server:
  port: 9080
cors:
  originPatterns: http://localhost:4200
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:6034/ProyectoPomodoro
    username: root
    password: my_secret_password
  jpa:
    hibernate:
      user-new-id-generator-mapping: false
      ddl-auto: update